### PR TITLE
Chinese tranditional  zh_HK version

### PR DESCRIPTION
**Pull request by hkkongou**
chinese tranditional version

### CODE REVIEW

**Review by TBlueF — CHANGES_REQUESTED** [review]
Ok! Only one thing is missing:
Please also add this to the [settings.js](https://github.com/BlueMap-Minecraft/BlueMapVue/blob/master/public/lang/settings.js) :)

**Comment by hkkongou** [comment]
> Ok! Only one thing is missing:
> Please also add this to the [settings.js](https://github.com/BlueMap-Minecraft/BlueMapVue/blob/master/public/lang/settings.js) :)

just changed :)

**Review by TBlueF — APPROVED** [review]
You changed it on a new branch on your fork, instead of this one. So i cherry-picked that change to the correct-branch for you :)
Looks good now! Thanks :)

**Comment by hkkongou** [comment]
> You changed it on a new branch on your fork, instead of this one. So i cherry-picked that change to the correct-branch for you :)
> Looks good now! Thanks :)

Thank you :) 
Sorry I am not that familiar with github /coding : (

**Pull request merged**
