### PR TITLE
Hungarian language added to the available languages

### PR DESCRIPTION
**Pull request by PiciAkk**

### CODE REVIEW

**Review by TBlueF — CHANGES_REQUESTED** [review]
Thanks! :)

One little thing:
if you could keep the settings.js sorted alphabetically by the languages `name`?
Like move your entry so it fits :)
That would be perfect 👍

**Comment by PiciAkk** [comment]
I fixed it :)

**Comment by TBlueF** [comment]
Awesome! Will be included in the next release :)

**Comment by PiciAkk** [comment]
Thanks! :)

**Pull request merged**
