### PR TITLE
Feat/change bundler

### PR DESCRIPTION
**Pull request by tsutoringo**
changed webpack to Vite.
In doing so, I did the following

## Removed the following dependencies
- core-js
- @vue/cli-plugin-babel
- @vue/cli-plugin-eslint
- @vue/cli-service
- babel-eslint
- eslint
- eslint-plugin-vue
- node-sass
- sass-loader
- vue-template-compiler
## The following dependencies were added instead
- @vitejs/plugin-vue2
- sass
- vite
- yaml

Changed npm script for Vite.
Changed all translation files to yaml.
@ Alias removed and changed to proper path.

Translated with www.DeepL.com/Translator (free version)

### CODE REVIEW

**Comment by tsutoringo** [comment]
I have an additional suggestion, how about changing it to pnpm?

**Comment by TBlueF** [comment]
I don't know anything about Vite and pnpm.
So can you please explain to my why you want to merge this change?
What are the benefits and what are possible drawbacks?

Also the GitHub-Action build needs to be fixed :)

**Comment by tsutoringo** [comment]
Vite allows for a better development environment with super fast startup.
More details here: https://vitejs.dev/

I think it is very fast compared to Webpack (I couldn't start with Webpack, so please try Vite).

When I changed to Vite, I couldn't read the language files with the import function, so I changed to yaml, but as a result, I think it is easier for users to edit.

As for pnpm, node_modules are managed by symbolic links, etc., which saves storage space and speeds up package installation.

**Comment by TBlueF** [comment]
Closing this: Vite is now used with the webapp being updated to Vue3

**Pull request closed without merging**
