### PR TITLE
Add Screenshot functionality

### PR DESCRIPTION
**Pull request by Nestu14**
- Added a button that saves a screenshot of the canvas in png format.
- The related i18n string has also been added to the fallback file.

### CODE REVIEW

**Comment by TBlueF** [comment]
See also: https://github.com/BlueMap-Minecraft/BlueMap/issues/218

**Review by TBlueF — CHANGES_REQUESTED** [review]
As talked about on Discord:

- The origin and license of the used icon are not known, so this icon can't be used
- I'd prefer the Screenshot-Button to be in the menu, somewhere around the `Reset Camera` button, since i want to be really careful about adding not too many buttons to the ControlBar
- Also add the l18n to the `en.js` *(and optionally other languages you might know)*

Optionally:
- Maybe some settings like requested in https://github.com/BlueMap-Minecraft/BlueMap/issues/218 ? :)

Thanks for the efforts! :)

**Comment by Nestu14** [comment]
The button has been moved to the menu and I have updated the i18n files that I could.
As for the options suggested in https://github.com/BlueMap-Minecraft/BlueMap/issues/218 for now I have implemented only PNG format as even JPEG has some inconsistencies in some browsers. However I have added the option for the image to be copied to the clipboard and should work in all modern browsers, except for Firefox that requires the user to enable the option.

**Comment by TBlueF** [comment]
Thanks :)

**Pull request merged**
