### PR TITLE
Change of translation to Polish

### PR DESCRIPTION
**Pull request by xartuu**
#### I'm very happy that our language is also available in your plugin!

Nevertheless, I changed a few things in the current translation. From the dash I'll list the changes I made:
- I corrected a spelling error in the translation.
- I finished the untranslated words.
- I used clearer vocabulary (easier to understand).
- In the information tab, I changed the table with keyboard shortcuts a bit to make it more readable and intuitive.
- I took the liberty of adding a text indicating that the translation is my own.

Additionally, in the `settings.js` file, I sorted the languages alphabetically by name.

##### On a personal note, I really like the new look of the UI!

### CODE REVIEW

**Review by TBlueF — APPROVED** [review]
Thanks!

**Comment by TBlueF** [comment]
@artuupl Hey! Sorry to bother you:

It's about this:
> I took the liberty of adding a text indicating that the translation is my own.

I made the mistake that i didn't read and reviewed your PR carefully enough, so i have not noticed that change and note when i merged your PR. I apologize for that!

First of all, I really support crediting Autors for their work and i definitely think everyone contributing to this project has to be mentioned somewhere!

However we need to have a unified place to do this, and do this for everyone! Files in this project are meant to evolve and be modified by many people over time. If we start to add autor-credits everywhere in the project, after some iterations those mentions will crowd the project and we get things like: `Author of this is A, edited by B, C fixed an issue and D added updated it to the newest version` :D
I want to avoid that ^^

So i think for this project we should just use GitHubs contributor-pages to have a list of Contributors and Authors:
BlueMap: https://github.com/BlueMap-Minecraft/BlueMap/graphs/contributors
BlueMapVue: https://github.com/BlueMap-Minecraft/BlueMapVue/graphs/contributors

I will also add links to those pages to all official download-pages and the ReadMe's.

### **Therefore, i request your permission to remove that credit of yours from this file again!**
If you don't want that, that is also fine, but i'll then have to revert your commit and undo all your awesome changes :(

Please give your answer to this soon :)

**Comment by xartuu** [comment]
I see your point. No problem, you can remove the note in the translation that it is of my authorship.

**Comment by TBlueF** [comment]
Thanks a lot <3

**Pull request merged**
